workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: 2.10.4
      xcode: latest
      cocoapods: default
    scripts:
      - echo $sentry_dsn > sentry_dsn
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release build ios --release -t lib/src/main.dart --no-codesign
      - |
        version=$(head -n 5 pubspec.yaml | tail -n 1 | cut -d ' ' -f 2)

        mkdir ~/Desktop/Payload \
        && cp -r build/ios/Release-iphoneos/Runner.app/ ~/Desktop/Payload/Runner.app/ \
        && cd ~/Desktop \
        && zip -ro JHenTai_${version}.ipa Payload \
        && rm -rf Payload
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
      - ~/Desktop/*.ipa
    publishing:
      email:
        recipients:
          - 905079589@qq.com
