name: jhentai
description: A flutter app for E-Hentai/EXHentai

publish_to: 'none'
version: 1.6.0+30

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  cookie_jar: 3.0.1
  dio_cookie_manager: ^2.0.0
  dio_cache_interceptor: ^3.2.6
  dio_cache_interceptor_db_store: ^4.1.1
  get: ^4.3.8
  get_storage: ^2.0.3
  extended_nested_scroll_view: ^5.0.0
  flukit: ^2.0.0
  html: ^0.15.0
  logger: ^1.1.0
  flutter_rating_bar: ^4.0.0
  waterfall_flow: ^3.0.2
  extended_image: ^6.0.1
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  collection: 1.15.0
  clipboard: ^0.1.3
  scrollable_positioned_list: ^0.2.3
  flutter_list_view: 1.1.12
  executor: ^2.2.2
  retry: ^3.1.0
  path: ^1.8.0
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.9
  flutter_slidable: ^1.2.0
  flutter_widget_from_html: ^0.8.5
  url_launcher: ^6.0.20
  like_button: ^2.0.4
  webview_flutter: ^3.0.1
  photo_view:
    git: https://gitee.com/jiangtian616/photo_view.git
  #    git: https://github.com/bluefireteam/photo_view.git
  reorderables: ^0.4.3
  package_info_plus: ^1.4.0
  file_picker: ^4.5.1
  local_auth: ^1.1.11
  blur: ^3.1.0
  flutter_windowmanager: ^0.2.0
  animate_do: ^2.1.0
  share_plus: ^4.0.4
  syncfusion_flutter_charts: ^20.1.47+1
  sentry_flutter: ^6.5.1
  archive: ^3.3.0
  image_size_getter: ^2.1.0
  fluttertoast: ^8.0.9
  battery_plus: ^2.1.3
  throttling: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.19.5
  drift_dev: ^1.5.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/
