blank_issues_enabled: true
contact_links:
  - name: Others
    url: https://github.com/jiangtian616/JHenTai/issues/new
    about: | 
      提交缺陷请使用第一条模板，否则将不予处理 / Please use the  first template to report bugs, otherwise they will not be processed
