blank_issues_enabled: true
contact_links:
  - name: Others
    url: https://github.com/jiangtian616/JHenTai/issues/new
    about: | 
      Bug和提问请使用上一条模板，否则将不予处理 / Please use the above template to report bugs or ask questions, otherwise they will not be processed